import json
import re

# I will paste the SOVEREIGN_LIBRARY data here as a python object
library = [
  {
    "id": 'h_wake_0430',
    "title": '04:30 Wake Up',
    "description": 'Beat the enemy to the battlefield.',
    "category": 'body',
    "system_tags": ['discipline', 'jocko'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Clock', "color": 'bg-slate-600' },
  },
  {
    "id": 'h_morning_sun',
    "title": 'Morning Sunlight',
    "description": 'Anchor circadian clock.',
    "category": 'body',
    "system_tags": ['circadian', 'huberman'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Sun', "color": 'bg-amber-500' },
  },
  {
    "id": 'h_salt_water',
    "title": 'Morning Salt',
    "description": '30oz Water + Electrolytes.',
    "category": 'body',
    "system_tags": ['hydration'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Droplets', "color": 'bg-blue-400' },
  },
  {
    "id": 'h_cold_plunge',
    "title": 'Cold Plunge',
    "description": 'Systemic inflammation reduction.',
    "category": 'body',
    "system_tags": ['recovery'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Thermometer', "color": 'bg-cyan-500' },
  },
  {
    "id": 'h_delay_caffeine',
    "title": 'Delay Caffeine',
    "description": 'Wait 90 mins before coffee.',
    "category": 'body',
    "system_tags": ['adenosine'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Coffee', "color": 'bg-amber-700' },
  },
  {
    "id": 'h_make_bed',
    "title": 'Make The Bed',
    "description": 'First task completed.',
    "category": 'mind',
    "system_tags": ['order'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'CheckCircle', "color": 'bg-emerald-600' },
  },
  {
    "id": 'h_meditation',
    "title": 'Meditation',
    "description": 'Mindfulness practice.',
    "category": 'spirit',
    "system_tags": ['mindfulness'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Wind', "color": 'bg-sky-400' },
  },
  {
    "id": 'h_breathwork',
    "title": 'Wim Hof Breath',
    "description": 'Hypoxic training.',
    "category": 'body',
    "system_tags": ['breath'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'morning' },
    "visuals": { "icon": 'Wind', "color": 'bg-blue-300' },
  },
  {
    "id": 'h_gratitude',
    "title": 'Gratitude Log',
    "description": 'Positive reinforcement.',
    "category": 'spirit',
    "system_tags": ['mindset'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Heart', "color": 'bg-pink-500' },
  },
  {
    "id": 'h_scripture',
    "title": 'Read Scripture',
    "description": 'Ancient wisdom.',
    "category": 'spirit',
    "system_tags": ['wisdom'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'BookOpen', "color": 'bg-yellow-600' },
  },
  {
    "id": 'h_zone_2',
    "title": 'Zone 2 Cardio',
    "description": 'Base aerobic capacity.',
    "category": 'body',
    "system_tags": ['endurance'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 4, "time_of_day": 'any' },
    "visuals": { "icon": 'Activity', "color": 'bg-emerald-500' },
  },
  {
    "id": 'h_heavy_lift',
    "title": 'Heavy Lift',
    "description": 'Compound resistance.',
    "category": 'body',
    "system_tags": ['strength'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 4, "time_of_day": 'afternoon' },
    "visuals": { "icon": 'Dumbbell', "color": 'bg-stone-500' },
  },
  {
    "id": 'h_rucking',
    "title": 'Rucking',
    "description": 'Weighted walking.',
    "category": 'body',
    "system_tags": ['endurance'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 2, "time_of_day": 'any' },
    "visuals": { "icon": 'Mountain', "color": 'bg-green-800' },
  },
  {
    "id": 'h_sprint',
    "title": 'VO2 Max Sprint',
    "description": 'HIIT intervals.',
    "category": 'body',
    "system_tags": ['vo2max'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Wind', "color": 'bg-red-500' },
  },
  {
    "id": 'h_mobility',
    "title": 'Mobility',
    "description": 'Joint maintenance.',
    "category": 'body',
    "system_tags": ['recovery'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'evening' },
    "visuals": { "icon": 'Smile', "color": 'bg-teal-500' },
  },
  {
    "id": 'h_grip',
    "title": 'Grip Training',
    "description": 'Hang/Carry.',
    "category": 'body',
    "system_tags": ['strength'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'any' },
    "visuals": { "icon": 'Target', "color": 'bg-stone-700' },
  },
  {
    "id": 'h_neck',
    "title": 'Neck Training',
    "description": 'Protective chassis.',
    "category": 'body',
    "system_tags": ['durability'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 2, "time_of_day": 'any' },
    "visuals": { "icon": 'Shield', "color": 'bg-stone-400' },
  },
  {
    "id": 'h_sport',
    "title": 'Sport / Play',
    "description": 'Dynamic movement.',
    "category": 'body',
    "system_tags": ['agility'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Trophy', "color": 'bg-yellow-500' },
  },
  {
    "id": 'h_10k_steps',
    "title": '10k Steps',
    "description": 'Base movement.',
    "category": 'body',
    "system_tags": ['recovery'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Footprints', "color": 'bg-green-400' },
  },
  {
    "id": 'h_sauna',
    "title": 'Sauna',
    "description": 'Heat shock.',
    "category": 'body',
    "system_tags": ['recovery'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 4, "time_of_day": 'evening' },
    "visuals": { "icon": 'Flame', "color": 'bg-orange-600' },
  },
  {
    "id": 'h_fasting',
    "title": 'Intermittent Fast',
    "description": 'Feeding window.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Utensils', "color": 'bg-yellow-500' },
  },
  {
    "id": 'h_protein',
    "title": 'Protein Target',
    "description": '1g per lb bodyweight.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Egg', "color": 'bg-red-700' },
  },
  {
    "id": 'h_no_sugar',
    "title": 'No Sugar',
    "description": 'Glycemic control.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Ban', "color": 'bg-red-600' },
  },
  {
    "id": 'h_no_alcohol',
    "title": 'Zero Alcohol',
    "description": 'Neurotoxin avoidance.',
    "category": 'body',
    "system_tags": ['health'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Ban', "color": 'bg-red-800' },
  },
  {
    "id": 'h_creatine',
    "title": 'Creatine',
    "description": '5g Monohydrate.',
    "category": 'body',
    "system_tags": ['supplements'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Zap', "color": 'bg-white' },
  },
  {
    "id": 'h_magnesium',
    "title": 'Magnesium',
    "description": 'Nervous system.',
    "category": 'body',
    "system_tags": ['supplements'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Zap', "color": 'bg-purple-500' },
  },
  {
    "id": 'h_omega3',
    "title": 'Omega-3',
    "description": 'Brain health.',
    "category": 'body',
    "system_tags": ['supplements'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Fish', "color": 'bg-orange-400' },
  },
  {
    "id": 'h_acv',
    "title": 'Apple Cider Vinegar',
    "description": 'Glycemic control.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'FlaskConical', "color": 'bg-amber-300' },
  },
  {
    "id": 'h_fiber',
    "title": 'Fiber',
    "description": 'Gut biome.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Leaf', "color": 'bg-green-400' },
  },
  {
    "id": 'h_cheat_meal',
    "title": 'Cheat Meal',
    "description": 'Metabolic reset.',
    "category": 'body',
    "system_tags": ['diet'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'RefreshCw', "color": 'bg-pink-500' },
  },
  {
    "id": 'h_deep_work',
    "title": 'Deep Work',
    "description": '90m Focus Block.',
    "category": 'business',
    "system_tags": ['productivity'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 5, "time_of_day": 'morning' },
    "visuals": { "icon": 'Brain', "color": 'bg-violet-600' },
  },
  {
    "id": 'h_read',
    "title": 'Read (Analog)',
    "description": 'Paper book.',
    "category": 'mind',
    "system_tags": ['learning'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'BookOpen', "color": 'bg-emerald-600' },
  },
  {
    "id": 'h_writing',
    "title": 'Writing',
    "description": 'Structured thought.',
    "category": 'mind',
    "system_tags": ['clarity'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'morning' },
    "visuals": { "icon": 'PenTool', "color": 'bg-blue-500' },
  },
  {
    "id": 'h_inbox_zero',
    "title": 'Inbox Zero',
    "description": 'Clear queues.',
    "category": 'business',
    "system_tags": ['organization'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 5, "time_of_day": 'afternoon' },
    "visuals": { "icon": 'Briefcase', "color": 'bg-blue-700' },
  },
  {
    "id": 'h_plan_tomorrow',
    "title": 'Plan Tomorrow',
    "description": 'Pre-deployment.',
    "category": 'business',
    "system_tags": ['prep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Target', "color": 'bg-slate-500' },
  },
  {
    "id": 'h_learn_skill',
    "title": 'Learn Skill',
    "description": 'Neuroplasticity.',
    "category": 'mind',
    "system_tags": ['learning'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'any' },
    "visuals": { "icon": 'Lightbulb', "color": 'bg-yellow-600' },
  },
  {
    "id": 'h_chess',
    "title": 'Chess',
    "description": 'Strategy game.',
    "category": 'mind',
    "system_tags": ['strategy'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 2, "time_of_day": 'any' },
    "visuals": { "icon": 'Swords', "color": 'bg-stone-600' },
  },
  {
    "id": 'h_outreach',
    "title": 'Outreach',
    "description": 'Pipeline generation.',
    "category": 'business',
    "system_tags": ['growth'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 5, "time_of_day": 'morning' },
    "visuals": { "icon": 'Network', "color": 'bg-indigo-600' },
  },
  {
    "id": 'h_audit_spend',
    "title": 'Audit Spend',
    "description": 'Financial check.',
    "category": 'asset',
    "system_tags": ['wealth'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Calculator', "color": 'bg-red-400' },
  },
  {
    "id": 'h_buy_bitcoin',
    "title": 'Buy Bitcoin',
    "description": 'DCA Hard Money.',
    "category": 'asset',
    "system_tags": ['wealth'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Gem', "color": 'bg-orange-500' },
  },
  {
    "id": 'h_dark_room',
    "title": 'Dark Room',
    "description": 'Blackout sleep.',
    "category": 'body',
    "system_tags": ['sleep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Moon', "color": 'bg-black' },
  },
  {
    "id": 'h_negative_viz',
    "title": 'Negative Viz',
    "description": 'Stoic prep.',
    "category": 'mind',
    "system_tags": ['stoicism'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'morning' },
    "visuals": { "icon": 'Skull', "color": 'bg-stone-800' },
  },
  {
    "id": 'h_memento_mori',
    "title": 'Memento Mori',
    "description": 'Remember death.',
    "category": 'spirit',
    "system_tags": ['stoicism'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Hourglass', "color": 'bg-stone-500' },
  },
  {
    "id": 'h_weekly_review',
    "title": 'Weekly Review',
    "description": 'Sunday strategy.',
    "category": 'mind',
    "system_tags": ['strategy'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'BookOpen', "color": 'bg-blue-800' },
  },
  {
    "id": 'h_social_detox',
    "title": 'Social Detox',
    "description": 'No media.',
    "category": 'mind',
    "system_tags": ['focus'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Ban', "color": 'bg-red-500' },
  },
  {
    "id": 'h_call_parents',
    "title": 'Call Parents',
    "description": 'Lineage.',
    "category": 'spirit',
    "system_tags": ['family'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'any' },
    "visuals": { "icon": 'Users', "color": 'bg-teal-600' },
  },
  {
    "id": 'h_date_night',
    "title": 'Date Night',
    "description": 'Partner focus.',
    "category": 'spirit',
    "system_tags": ['relationship'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 1, "time_of_day": 'evening' },
    "visuals": { "icon": 'Heart', "color": 'bg-pink-600' },
  },
  {
    "id": 'h_play_kids',
    "title": 'Play w/ Kids',
    "description": 'Undistracted.',
    "category": 'spirit',
    "system_tags": ['family'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Smile', "color": 'bg-yellow-400' },
  },
  {
    "id": 'h_gear_prep',
    "title": 'Gear Prep',
    "description": 'Kit staging.',
    "category": 'body',
    "system_tags": ['prep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Briefcase', "color": 'bg-slate-700' },
  },
  {
    "id": 'h_clean_water',
    "title": 'Clean Water',
    "description": 'Filtered only.',
    "category": 'body',
    "system_tags": ['health'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Droplets', "color": 'bg-cyan-600' },
  },
  {
    "id": 'h_grounding',
    "title": 'Grounding',
    "description": 'Earth contact.',
    "category": 'body',
    "system_tags": ['recovery'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'morning' },
    "visuals": { "icon": 'Sprout', "color": 'bg-green-600' },
  },
  {
    "id": 'h_nature_walk',
    "title": 'Nature Walk',
    "description": 'Green space.',
    "category": 'mind',
    "system_tags": ['calm'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 2, "time_of_day": 'any' },
    "visuals": { "icon": 'Leaf', "color": 'bg-green-500' },
  },
  {
    "id": 'h_cook_meal',
    "title": 'Cook Meal',
    "description": 'Scratch cooking.',
    "category": 'body',
    "system_tags": ['nutrition'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Flame', "color": 'bg-orange-500' },
  },
  {
    "id": 'h_box_breath',
    "title": 'Box Breathing',
    "description": 'Stress reset.',
    "category": 'mind',
    "system_tags": ['calm'],
    "default_config": { "frequency_type": 'FREQUENCY', "target_days": 3, "time_of_day": 'any' },
    "visuals": { "icon": 'Wind', "color": 'bg-blue-200' },
  },
  {
    "id": 'h_no_phone',
    "title": 'No Phone',
    "description": 'Physical separation.',
    "category": 'mind',
    "system_tags": ['focus'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'any' },
    "visuals": { "icon": 'Ban', "color": 'bg-red-400' },
  },
  {
    "id": 'h_sleep_track',
    "title": 'Sleep Track',
    "description": 'Quantify recovery.',
    "category": 'body',
    "system_tags": ['data'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'morning' },
    "visuals": { "icon": 'Moon', "color": 'bg-indigo-500' },
  },
  {
    "id": 'h_blue_block',
    "title": 'Blue Block',
    "description": 'Melatonin protection.',
    "category": 'body',
    "system_tags": ['sleep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Glasses', "color": 'bg-orange-500' },
  },
  {
    "id": 'h_temp_drop',
    "title": 'Temp Drop',
    "description": 'Cool sleep.',
    "category": 'body',
    "system_tags": ['sleep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Thermometer', "color": 'bg-cyan-800' },
  },
  {
    "id": 'h_mouth_tape',
    "title": 'Mouth Tape',
    "description": 'Nasal breath.',
    "category": 'body',
    "system_tags": ['sleep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Smile', "color": 'bg-teal-700' },
  },
  {
    "id": 'h_digital_dark',
    "title": 'Digital Dark',
    "description": 'Zero screens.',
    "category": 'mind',
    "system_tags": ['sleep'],
    "default_config": { "frequency_type": 'ABSOLUTE', "target_days": 7, "time_of_day": 'evening' },
    "visuals": { "icon": 'Moon', "color": 'bg-indigo-900' },
  }
]

print("DELETE FROM habits;")
for habit in library:
    metadata = json.dumps({
        "config": habit["default_config"],
        "visuals": habit["visuals"],
        "system_tags": habit["system_tags"],
        "category": habit["category"]
    }).replace("'", "''")

    # Simple escape for strings
    title = habit["title"].replace("'", "''")
    description = habit["description"].replace("'", "''")
    habit_id = habit["id"]

    # NOTE: Assuming the table schema matches what useHabits expects
    # 'habit_id' seems to be the column for the unique string ID (h_wake_0430).
    # 'status' defaults to active? Or should we set them all to something?
    # The prompt says: "Render ALL inactive habits here. Allow the user to 'Equip' them".
    # So we should probably insert them as 'inactive' or 'archived' initially?
    # Or insert them into a library table?
    # Wait, the 'habits' table seems to be USER habits.
    # The prompt says: "1. DELETE FROM habits; 2. INSERT the full 60-item library."
    # This implies we are resetting the USER'S habits to have ALL 60 items available in their "Atom Ledger" (inactive/archived) or maybe active?
    # "Section 3: ATOM LEDGER (The Reserves) - Render ALL inactive habits here."
    # So we should insert them with status = 'archived' or 'inactive'.
    # I'll use 'archived' based on previous context.

    print(f"INSERT INTO habits (habit_id, title, description, status, metadata) VALUES ('{habit_id}', '{title}', '{description}', 'archived', '{metadata}');")
