import fs from 'fs';
import path from 'path';

const habitsPayload = [
  { "slug": "daily_steps", "title": "Daily Steps", "category": "bio_rig", "type": "metric", "target_value": 10000, "unit": "steps", "metadata": { "visuals": { "icon": "Footprints", "theme": "bio_emerald", "is_ring": true }, "compiler": { "atom": "Movement Baseline", "step": "Incidental movement throughout the day.", "why": "Biological engine maintenance. Prevents the 'Sedentary Drift'. [Universal]", "expert": "Universal" } } },
  { "slug": "morning_sun", "title": "Morning Sun", "category": "bio_rig", "type": "duration", "target_value": 15, "unit": "minutes", "metadata": { "visuals": { "icon": "Sun", "theme": "bio_emerald" }, "compiler": { "atom": "Photon Anchoring", "step": "View outdoor light within 30m of waking. No sunglasses.", "why": "Resets the central clock (SCN) and sets the sleep timer. [Panda]", "expert": "Dr. Satchin Panda" } } },
  { "slug": "fasting", "title": "Intermittent Fasting", "category": "bio_rig", "type": "duration", "target_value": 16, "unit": "hours", "metadata": { "visuals": { "icon": "Timer", "theme": "asset_lime" }, "compiler": { "atom": "Metabolic Switch", "step": "16-hour fast. Water and black coffee only.", "why": "Triggers autophagy and stabilizes insulin sensitivity. [Attia]", "expert": "Dr. Peter Attia" } } },
  { "slug": "sauna", "title": "Sauna / Heat", "category": "bio_rig", "type": "duration", "target_value": 20, "unit": "minutes", "metadata": { "visuals": { "icon": "Flame", "theme": "combat_red" }, "compiler": { "atom": "Hormetic Heat", "step": "Dry sauna at 174°F minimum. No water mid-session.", "why": "Activates Heat Shock Proteins to prevent protein misfolding. [Patrick]", "expert": "Dr. Rhonda Patrick" } } },
  { "slug": "cold_plunge", "title": "Cold Exposure", "category": "bio_rig", "type": "duration", "target_value": 3, "unit": "minutes", "metadata": { "visuals": { "icon": "Snowflake", "theme": "oxygen_cyan" }, "compiler": { "atom": "Cold Shock", "step": "Neck-deep submersion in <50°F water. Minimize movement.", "why": "Triggers 250% dopamine increase and mental callousing. [Huberman]", "expert": "Dr. Andrew Huberman" } } },
  { "slug": "heavy_lifting", "title": "Heavy Lifting", "category": "kinetic_core", "type": "metric", "target_value": 1, "unit": "session", "metadata": { "visuals": { "icon": "Dumbbell", "theme": "slate_steel" }, "compiler": { "atom": "Neural Drive", "step": "Compound movements (Squat/Press). 3-5 Reps/Sets.", "why": "Muscular strength is the primary predictor of healthspan. [Galpin]", "expert": "Dr. Andy Galpin" } } },
  { "slug": "deep_work", "title": "Deep Work", "category": "kinetic_core", "type": "duration", "target_value": 90, "unit": "minutes", "metadata": { "visuals": { "icon": "Zap", "theme": "neural_violet" }, "compiler": { "atom": "Cognitive Isolation", "step": "No phone. No internet. Single-task focus on the lead domino.", "why": "High-quality output = (Time Spent) x (Intensity). [Newport]", "expert": "Cal Newport" } } },
  { "slug": "shadow_audit", "title": "Shadow Audit", "category": "black_box", "type": "boolean", "target_value": 1, "unit": "audit", "metadata": { "visuals": { "icon": "PenTool", "theme": "warning_amber" }, "compiler": { "atom": "Radical Honesty", "step": "5m review of failures and lies told today. Zero excuses.", "why": "You cannot fix what you refuse to look at. [Stoic]", "expert": "Aurelius" } } },
  { "slug": "ready_state", "title": "Ready State", "category": "bio_rig", "type": "duration", "target_value": 10, "unit": "minutes", "metadata": { "visuals": { "icon": "RefreshCw", "theme": "bio_emerald" }, "compiler": { "atom": "Tissue Maintenance", "step": "Couch stretch and deep squat hold.", "why": "Offset the contractures caused by 21st-century sitting. [Starrett]", "expert": "Kelly Starrett" } } },
  { "slug": "nasal_breathing", "title": "Nasal Breathing", "category": "bio_rig", "type": "boolean", "target_value": 1, "unit": "compliance", "metadata": { "visuals": { "icon": "Wind", "theme": "oxygen_cyan" }, "compiler": { "atom": "Carbon Tolerance", "step": "Breathe only through nose during exercise and sleep.", "why": "Increases oxygen delivery efficiency via the Bohr Effect. [McKeown]", "expert": "Patrick McKeown" } } },
  { "slug": "protein_loading", "title": "Protein Load", "category": "bio_rig", "type": "metric", "target_value": 30, "unit": "grams", "metadata": { "visuals": { "icon": "Dna", "theme": "asset_lime" }, "compiler": { "atom": "Leucine Trigger", "step": "30g+ protein in the first meal.", "why": "Threshold to initiate Muscle Protein Synthesis. [Layman]", "expert": "Dr. Donald Layman" } } },
  { "slug": "sleep_hygiene", "title": "Deep Sleep", "category": "bio_rig", "type": "duration", "target_value": 8, "unit": "hours", "metadata": { "visuals": { "icon": "Moon", "theme": "bio_rig" }, "compiler": { "atom": "Glymphatic Clearance", "step": "Cool room (65°F). Total darkness.", "why": "Clears amyloid beta neurotoxins from the brain. [Walker]", "expert": "Dr. Matthew Walker" } } },
  { "slug": "vo2_max", "title": "VO2 Max", "category": "telemetry", "type": "metric", "target_value": 1, "unit": "session", "metadata": { "visuals": { "icon": "Activity", "theme": "telemetry" }, "compiler": { "atom": "Aerobic Power", "step": "4 mins Max Effort, 4 mins Rest. Repeat 4x.", "why": "Cardiorespiratory fitness is the strongest correlate to lifespan. [Attia]", "expert": "Dr. Peter Attia" } } },
  { "slug": "make_bed", "title": "Make Bed", "category": "kinetic_core", "type": "boolean", "target_value": 1, "unit": "mission", "metadata": { "visuals": { "icon": "Shield", "theme": "slate_steel" }, "compiler": { "atom": "Discipline Baseline", "step": "Precision bed-make upon waking. No loose corners.", "why": "Small victories establish the standard of excellence. [Jocko]", "expert": "Jocko Willink" } } },
  { "slug": "prayer_stillness", "title": "Stillness", "category": "nav_computer", "type": "duration", "target_value": 10, "unit": "minutes", "metadata": { "visuals": { "icon": "Heart", "theme": "ghost_white" }, "compiler": { "atom": "Narrative Control", "step": "10m of prayer or meditation for others.", "why": "Interrupts the selfish ego and resets Internal Force. [Aurelius]", "expert": "Marcus Aurelius" } } },
  { "slug": "good_deed", "title": "Secret Deed", "category": "armor_plating", "type": "boolean", "target_value": 1, "unit": "act", "metadata": { "visuals": { "icon": "Heart", "theme": "neural_violet" }, "compiler": { "atom": "Character Forge", "step": "One helpful act. They must never know it was you.", "why": "Removes the dopamine hit of praise to build integrity. [Stoic]" } } },
  { "slug": "memento_mori", "title": "Remember Death", "category": "armor_plating", "type": "boolean", "target_value": 1, "unit": "session", "metadata": { "visuals": { "icon": "Lock", "theme": "ghost_white" }, "compiler": { "atom": "Perspective Strike", "step": "Reflect for 2m: 'This could be my last day.'", "why": "Kills procrastination instantly. Realizing time is finite. [Seneca]", "expert": "Seneca" } } },
  { "slug": "digital_sunset", "title": "Digital Sunset", "category": "black_box", "type": "boolean", "target_value": 1, "unit": "sunset", "metadata": { "visuals": { "icon": "Moon", "theme": "sunset_indigo" }, "compiler": { "atom": "Melatonin Protection", "step": "Screens off 60m before bed.", "why": "Ensures deep REM and hormonal reset. [Walker]", "expert": "Dr. Matthew Walker" } } },
  { "slug": "glycemic_defense", "title": "Sugar Defense", "category": "bio_rig", "type": "boolean", "target_value": 1, "unit": "day", "metadata": { "visuals": { "icon": "Lock", "theme": "combat_red" }, "compiler": { "atom": "Metabolic Shield", "step": "Zero refined sugar or liquid calories for 24h.", "why": "Reduces systemic inflammation and energy crashes. [Lustig]", "expert": "Dr. Robert Lustig" } } },
  { "slug": "social_sync", "title": "Social Sync", "category": "the_ally", "type": "boolean", "target_value": 1, "unit": "call", "metadata": { "visuals": { "icon": "Users", "theme": "maxi_blue" }, "compiler": { "atom": "Tribe Connection", "step": "Connect with one person for 10+ mins.", "why": "Social isolation is a primary biological stressor. [Conti]", "expert": "Dr. Paul Conti" } } },
  { "slug": "skill_acquisition", "title": "Skill Build", "category": "nav_computer", "type": "duration", "target_value": 30, "unit": "minutes", "metadata": { "visuals": { "icon": "BookOpen", "theme": "neural_violet" }, "compiler": { "atom": "Neural Plasticity", "step": "30m practice on a high-leverage skill.", "why": "The mind is for training, not just storage. [Huberman]", "expert": "Dr. Andrew Huberman" } } },
  { "slug": "daily_shutdown", "title": "Work Shutdown", "category": "black_box", "type": "boolean", "target_value": 1, "unit": "ritual", "metadata": { "visuals": { "icon": "RotateCcw", "theme": "sunset_indigo" }, "compiler": { "atom": "Cognitive Closure", "step": "Review tomorrow's Big 3. Say 'Shutdown Complete'.", "why": "Clears attention residue and protects recovery. [Newport]", "expert": "Cal Newport" } } },
  { "slug": "dead_hang", "title": "Dead Hang", "category": "telemetry", "type": "metric", "target_value": 120, "unit": "seconds", "metadata": { "visuals": { "icon": "Anchor", "theme": "telemetry" }, "compiler": { "atom": "Force Output", "step": "Hang from a bar. Active shoulders. Total 120s.", "why": "Grip strength correlates with all-cause mortality. [Bohannon]", "expert": "Peter Attia" } } },
  { "slug": "box_breathing", "title": "Box Breath", "category": "armor_plating", "type": "duration", "target_value": 5, "unit": "minutes", "metadata": { "visuals": { "icon": "Wind", "theme": "oxygen_cyan" }, "compiler": { "atom": "Vagus Nerve Stim", "step": "Inhale 4s, Hold 4s, Exhale 4s, Hold 4s.", "why": "Instantly restores cognitive control. [McKeown]", "expert": "Patrick McKeown" } } },
  { "slug": "touch_grass", "title": "Touch Grass", "category": "bio_rig", "type": "duration", "target_value": 15, "unit": "minutes", "metadata": { "visuals": { "icon": "Trees", "theme": "bio_emerald" }, "compiler": { "atom": "Panoramic Vision", "step": "15m outside. Look at horizon. No phone.", "why": "Natural fractals reduce rumination. [Bratman]", "expert": "Dr. Gregory Bratman" } } },
  { "slug": "inbox_zero", "title": "Inbox Zero", "category": "kinetic_core", "type": "boolean", "target_value": 1, "unit": "process", "metadata": { "visuals": { "icon": "Mail", "theme": "slate_steel" }, "compiler": { "atom": "Open Loop Closure", "step": "Process inbox until empty. Archive or Task.", "why": "Unfinished tasks act as a cognitive energy leak. [Ferriss]", "expert": "Tim Ferriss" } } },
  { "slug": "digital_air_gap", "title": "Phone Air-Gap", "category": "black_box", "type": "duration", "target_value": 60, "unit": "minutes", "metadata": { "visuals": { "icon": "Lock", "theme": "black_box" }, "compiler": { "atom": "Dopamine Reset", "step": "Phone in a separate room for 1 hour.", "why": "Restores dopamine receptor sensitivity. [Lembke]", "expert": "Dr. Anna Lembke" } } },
  { "slug": "agency_audit", "title": "Mind Audit", "category": "black_box", "type": "boolean", "target_value": 1, "unit": "entry", "metadata": { "visuals": { "icon": "Brain", "theme": "nav_computer" }, "compiler": { "atom": "Narrative Control", "step": "Identify 'Defense' vs 'Generative' drive.", "why": "Regain agency over trauma reactions. [Conti]", "expert": "Dr. Paul Conti" } } },
  { "slug": "leverage_audit", "title": "Leverage Audit", "category": "nav_computer", "type": "boolean", "target_value": 1, "unit": "review", "metadata": { "visuals": { "icon": "TrendingUp", "theme": "kinetic_core" }, "compiler": { "atom": "Input/Output Audit", "step": "Did you use Code, Media, or Capital today?", "why": "Wealth = Leverage x Judgment. [Naval]", "expert": "Naval Ravikant" } } },
  { "slug": "fasted_walk", "title": "Fasted Walk", "category": "bio_rig", "type": "duration", "target_value": 20, "unit": "minutes", "metadata": { "visuals": { "icon": "Activity", "theme": "bio_rig" }, "compiler": { "atom": "Lipolysis", "step": "20m walk before first calorie.", "why": "Mobilize fatty acids immediately upon waking. [Horowitz]", "expert": "Dr. Barry Horowitz" } } },
  { "slug": "cold_bedroom", "title": "Cold Room", "category": "bio_rig", "type": "boolean", "target_value": 1, "unit": "check", "metadata": { "visuals": { "icon": "Thermometer", "theme": "bio_rig" }, "compiler": { "atom": "Core Temp Drop", "step": "Bedroom at 65°F (18°C) before sleep.", "why": "Biological trigger for deep sleep onset. [Walker]", "expert": "Dr. Matthew Walker" } } },
  { "slug": "nsdr_reset", "title": "Neural Reboot", "category": "bio_rig", "type": "duration", "target_value": 20, "unit": "minutes", "metadata": { "visuals": { "icon": "Zap", "theme": "neural_violet" }, "compiler": { "atom": "Dopamine Reset", "step": "10-20 min audio guide (Yoga Nidra).", "why": "Cognitive recovery without sleep. [Huberman]", "expert": "Dr. Andrew Huberman" } } },
  { "slug": "creatine_load", "title": "Brain Fuel", "category": "bio_rig", "type": "metric", "target_value": 5, "unit": "grams", "metadata": { "visuals": { "icon": "Zap", "theme": "asset_lime" }, "compiler": { "atom": "ATP Reservoir", "step": "5g Monohydrate daily. Anytime.", "why": "Improves anaerobic power and cognition. [Attia]", "expert": "Dr. Peter Attia" } } },
  { "slug": "taking_souls", "title": "Take Souls", "category": "kinetic_core", "type": "boolean", "target_value": 1, "unit": "mission", "metadata": { "visuals": { "icon": "Flame", "theme": "combat_red" }, "compiler": { "atom": "Mental Callousing", "step": "Train until the mind wants to quit.", "why": "Override the brain's safety governor. [Goggins]", "expert": "David Goggins" } } },
  { "slug": "cookie_jar", "title": "Cookie Jar", "category": "telemetry", "type": "boolean", "target_value": 1, "unit": "reflection", "metadata": { "visuals": { "icon": "Trophy", "theme": "warning_amber" }, "compiler": { "atom": "Suffering Audit", "step": "Recall a moment of suffering you overcame.", "why": "Fuel for the current struggle. [Goggins]", "expert": "David Goggins" } } },
  { "slug": "accountability_mirror", "title": "Truth Mirror", "category": "black_box", "type": "boolean", "target_value": 1, "unit": "audit", "metadata": { "visuals": { "icon": "Eye", "theme": "ghost_white" }, "compiler": { "atom": "Radical Truth", "step": "Face the mirror. State your insecurities.", "why": "Strip the ego to build mental callous. [Goggins]", "expert": "David Goggins" } } },
  { "slug": "carbon_tolerance", "title": "Breath Check", "category": "telemetry", "type": "metric", "target_value": 60, "unit": "seconds", "metadata": { "visuals": { "icon": "Wind", "theme": "oxygen_cyan" }, "compiler": { "atom": "Exhale Timer", "step": "Measure duration of a single exhale.", "why": "Proxy for stress resilience. [Mackenzie]", "expert": "Brian Mackenzie" } } },
  { "slug": "recovery_sync", "title": "Recovery Sync", "category": "the_ally", "type": "boolean", "target_value": 1, "unit": "meeting", "metadata": { "visuals": { "icon": "Sun", "theme": "maxi_blue" }, "compiler": { "atom": "Sovereign Spirit", "step": "Attend meeting or Service. No isolation.", "why": "Honoring the personal mission. Isolation is drift.", "expert": "Founder" } } },
  { "slug": "amor_fati", "title": "Amor Fati", "category": "armor_plating", "type": "boolean", "target_value": 1, "unit": "acceptance", "metadata": { "visuals": { "icon": "RefreshCw", "theme": "ghost_white" }, "compiler": { "atom": "Love of Fate", "step": "Embrace a current obstacle as fuel.", "why": "The hindrance is the path. [Aurelius]", "expert": "Marcus Aurelius" } } },
  { "slug": "dichotomy_control", "title": "Control Audit", "category": "armor_plating", "type": "boolean", "target_value": 1, "unit": "logic", "metadata": { "visuals": { "icon": "Shield", "theme": "ghost_white" }, "compiler": { "atom": "Focus Strike", "step": "Discard worries outside your control.", "why": "Zero energy leak on externals. [Epictetus]", "expert": "Epictetus" } } },
  { "slug": "sleep_cocktail", "title": "Sleep Stack", "category": "bio_rig", "type": "boolean", "target_value": 1, "unit": "compliance", "metadata": { "visuals": { "icon": "Moon", "theme": "neural_violet" }, "compiler": { "atom": "Neuro-Downreg", "step": "Mg Threonate + Theanine 60m pre-bed.", "why": "Reduce sleep latency. [Huberman]", "expert": "Dr. Andrew Huberman" } } },
  { "slug": "forty_percent", "title": "40% Override", "category": "kinetic_core", "type": "boolean", "target_value": 1, "unit": "push", "metadata": { "visuals": { "icon": "Zap", "theme": "combat_red" }, "compiler": { "atom": "Governor Bypass", "step": "Push for 5 more when mind says 'done'.", "why": "The mind quits before the body. [Goggins]", "expert": "David Goggins" } } }
];

const protocolsPayload = [
  { "name": "Atlas Golden Set", "expert_voice": "Founder", "theme_override": "maxi_blue", "description": "The foundation for Rig stability.", "habits": ["morning_sun", "deep_work", "daily_steps", "shadow_audit", "digital_sunset"] },
  { "name": "Neuro-Rig Stack", "expert_voice": "Andrew Huberman", "theme_override": "oxygen_cyan", "description": "Biological hardware optimization.", "habits": ["morning_sun", "cold_plunge", "nsdr_reset", "digital_sunset", "sleep_cocktail"] },
  { "name": "Iron Mind", "expert_voice": "David Goggins", "theme_override": "combat_red", "description": "Callous the mind through suffering.", "habits": ["accountability_mirror", "heavy_lifting", "taking_souls", "cookie_jar", "forty_percent"] },
  { "name": "Attia Centenarian", "expert_voice": "Peter Attia", "theme_override": "bio_emerald", "description": "Training today for the 'Marginal Decade'.", "habits": ["zone_2_cardio", "heavy_lifting", "fasting", "sauna"] },
  { "name": "Jocko Discipline", "expert_voice": "Jocko Willink", "theme_override": "slate_steel", "description": "Military-grade standard for daily execution.", "habits": ["make_bed", "deep_work", "shadow_audit", "glycemic_defense"] },
  { "name": "The Stoic", "expert_voice": "Marcus Aurelius", "theme_override": "ghost_white", "description": "Ancient logic for modern chaos.", "habits": ["memento_mori", "amor_fati", "prayer_stillness", "good_deed"] }
];

const sql = `
-- Disable RLS to allow the system sync
ALTER TABLE library_protocols DISABLE ROW LEVEL SECURITY;

-- 1. SYNC HABIT LIBRARY
UPDATE library_habits h
SET
    title = j.val->>'title',
    category = j.val->>'category',
    type = j.val->>'type',
    target_value = (j.val->>'target_value')::numeric,
    unit = j.val->>'unit',
    description = (j.val->'metadata'->'compiler'->>'step'),
    metadata = j.val->'metadata'
FROM (
    SELECT jsonb_array_elements($$
    ${JSON.stringify(habitsPayload)}
    $$::jsonb) AS val
) AS j
WHERE h.slug = j.val->>'slug';

-- 2. SYNC PROTOCOL STACKS
TRUNCATE TABLE library_protocols;
INSERT INTO library_protocols (title, name, description, category, habits)
SELECT
    p->>'name',
    p->>'name',
    p->>'description',
    p->>'expert_voice',
    ARRAY(SELECT jsonb_array_elements_text(p->'habits'))
FROM jsonb_array_elements($$
${JSON.stringify(protocolsPayload)}
$$::jsonb) AS p;

-- Re-enable RLS after the sync is complete
ALTER TABLE library_protocols ENABLE ROW LEVEL SECURITY;
`;

fs.writeFileSync(path.resolve(process.cwd(), 'client/src/scripts/final_sync.sql'), sql);
console.log('SQL file generated at client/src/scripts/final_sync.sql');
