-- FIX THE MISSING COLUMNS (Stops the "Update Failed" error)
ALTER TABLE habits
ADD COLUMN IF NOT EXISTS streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS longest_streak INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS total_completions INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_completed_at TIMESTAMP WITH TIME ZONE;
